### ISSUE TITLE
Feature request: set model temperature in settings

### ISSUE THREAD

**Issue by AeroXi** [anc95/writely#37]
https://platform.openai.com/docs/api-reference/chat/create#chat/create-temperature
<img width="530" alt="image" src="https://user-images.githubusercontent.com/31943024/229331525-9600761f-5b73-4dd2-a80e-c175e88f9f3a.png">
The default temperature is 1. This feature will be useful if users want more control over the output, either more creative or more accurate. 
Summary and translation usually need lower temperature to improve precision.
It can be a number input in settings, and later we can add some common presets according to user feedback.
example:
![image](https://user-images.githubusercontent.com/31943024/229331684-43ff21ed-f121-4021-b400-97fe2c8d9bb8.png)

**Comment by AeroXi** [comment]
If need, I can implement this.

**Comment by anc95** [comment]
@AeroXi Yes. Thank you. Appreciate it if you can help with this feature. My advice is let's have preset in the first version (because most users actually don't know what's the meaning of temperature). And in the future we can add a slider, users can set any value between 0-2. What do you think about this?

Agree with you on this in particular. the different prompts may need different temperature settings. maybe in the future, we can support config different temperature settings for different custom instructions

**Comment by AeroXi** [comment]
Yes, I suggest three levels of temperature:
精准 accurate 0
平衡 balance 0.7
创造力 creative 1
0.7 is the default value in openai playground, it's a good starting point.
We can set default to 1 to keep it consistent with the previous version.

**Comment by AeroXi** [comment]
> the different prompts may need different temperature settings. maybe in the future, we can support config different temperature settings for different custom instructions

Yes, we can add better prompt template settings in the future
